# https://github.com/redhat-et/AI-for-edge-microshift-demo
---
apiVersion: edge.kyst.kube/v1alpha1
kind: ConfigSpec
metadata:
  name: ai4edge
spec:
  content:
  - https://github.com/redhat-et/AI-for-edge-microshift-demo/raw/main/server/cam-server.yaml
  - https://github.com/redhat-et/AI-for-edge-microshift-demo/raw/main/wifi-ap/cam-ap.yaml
---
apiVersion: edge.kyst.kube/v1alpha1
kind: DeviceGroup
metadata:
  name: ai4edge
spec:
  configSpecName: ai4edge
---
apiVersion: edge.kyst.kube/v1alpha1
kind: InventoryDevice
metadata:
  name: ai4edge
  labels:
    edge.kyst.kube/device-group-name: ai4edge
