apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{.Name}}
  labels:
    group: use-plugin
spec:
  destination:
    namespace: argocd-scalability
    server: https://54.172.220.0:6443
  project: default
  source:
    path: examples/kubernetes/guestbook/deploy-scalability/
    plugin:
      name: wrap4kyst-scalability
    repoURL: https://github.com/edge-experiments/kyst-configurations.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
