apiVersion: v1
kind: ConfigMap
metadata:
  namespace: default
  name: nginx-cm
data:
  nginx.conf: |
    user nginx;
    worker_processes  1;
    events {
      worker_connections  10240;
    }
    http {
      server {
          listen       80;
          server_name  localhost;
          location / {
            root   /usr/share/nginx/html;
            # replace index.html with my-index.html for demo
            index  index.html index.htm;
        }
      }
    }
---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: default
  name: nginx-my-index
data:
  my-index.html: |
    <!DOCTYPE html>
    <html>
    <head>
    <title>Welcome to MY nginx!</title>
    <style>
        body {
            width: 35em;
            margin: 0 auto;
            font-family: Tahoma, Verdana, Arial, sans-serif;
        }
    </style>
    </head>
    <body>
    <h1>Welcome to MY nginx!</h1>
    <p>If you see this page, the nginx web server is successfully installed and
    working. Further configuration is required.</p>

    <p>For online documentation and support please refer to
    <a href="http://nginx.org/">nginx.org</a>.<br/>
    Commercial support is available at
    <a href="http://nginx.com/">nginx.com</a>.</p>

    <p><em>Thank you for using nginx.</em></p>
    </body>
    </html>
