---
apiVersion: v1
kind: ConfigMap
metadata:
  name: repqad-config
data:
    # humidity, temperature, cpu_temp, gyroscope
  items_to_send: |
    humidity, temperature
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: reportqad-deployment
spec:
  selector:
    matchLabels:
      app: reportqad
  replicas: 1
  template:
    metadata:
      labels:
        app: reportqad
    spec:
      containers:
      - name: reportqad
        image: quay.io/kproche0/report-qad:latest
        imagePullPolicy: Always
        command: ["/bin/bash","-c","sleep infinity"]
        command: ["python3","report-qad.py"]
        securityContext:
          privileged: False
        volumeMounts:
        - name: config-volume
          mountPath: /repqad/config
        env:
          - name: WebSocketURL
            value: "wss://edgepilognodered2021.mybluemix.net/ws/chat2" # ==> https://edgepilognodered2021.mybluemix.net/chat2
          - name: LOGGER_DELAY
            value: "0.2"
          - name: TZ
            value: "America/Los_Angeles"
          - name: CPUTF
            value: "1.5538"
          - name: CHAT_USER
            value: "kyst-app"
          - name: LOGGER_CONFIG
            value: "/repqad/config"
          - name: LOG_RAW_IMAGES
            value: "False"
          - name: NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
        ports:
         - containerPort: 8095
      volumes:
        - name: config-volume
          configMap:
            name: repqad-config
