apiVersion: work.open-cluster-management.io/v1
kind: ManifestWork
metadata:
  namespace: cluster1
  name: example-manifestwork
spec:
  workload:
    manifests:
    - apiVersion: v1
      kind: ServiceAccount
      metadata:
        namespace: default
        name: nginx-sa
    - apiVersion: apps/v1
      kind: Deployment
      metadata:
        namespace: default
        name: nginx-deployment
        labels:
          app: nginx
      spec:
        replicas: 3
        selector:
          matchLabels:
            app: nginx
        template:
          metadata:
            labels:
              app: nginx
          spec:
            serviceAccountName: nginx-sa
            containers:
            - name: nginx
              image: nginx:1.14.2
              ports:
              - containerPort: 80
              volumeMounts:
              - name: nginx-conf
                mountPath: /etc/nginx/nginx.conf
                subPath: nginx.conf
                readOnly: true
              - name: nginx-my-index
                mountPath: /usr/share/nginx/html/my-index.html
                subPath: my-index.html
                readOnly: true
            volumes:
            - name: nginx-conf
              configMap:
                name: nginx-cm
                items:
                  - key: nginx.conf
                    path: nginx.conf
            - name: nginx-my-index
              configMap:
                name: nginx-my-index
                items:
                  - key: my-index.html
                    path: my-index.html
    - apiVersion: v1
      kind: Service
      metadata:
        labels:
          app: nginx
        namespace: default
        name: nginx-svc
      spec:
        ports:
        - nodePort: 32064
          port: 80
          protocol: TCP
          targetPort: 80
        selector:
          app: nginx
        type: NodePort
    - apiVersion: v1
      kind: ConfigMap
      metadata:
        namespace: default
        name: nginx-cm
      data:
        nginx.conf: |
          user nginx;
          worker_processes  1;
          events {
            worker_connections  10240;
          }
          http {
            server {
                listen       80;
                server_name  localhost;
                location / {
                  root   /usr/share/nginx/html;
                  # replace index.html with my-index.html for demo
                  index  index.html index.htm;
              }
            }
          }
    - apiVersion: v1
      kind: ConfigMap
      metadata:
        namespace: default
        name: nginx-my-index
      data:
        my-index.html: |
          <!DOCTYPE html>
          <html>
          <head>
          <title>Welcome to MY nginx!</title>
          <style>
              body {
                  width: 35em;
                  margin: 0 auto;
                  font-family: Tahoma, Verdana, Arial, sans-serif;
              }
          </style>
          </head>
          <body>
          <h1>Welcome to MY nginx!</h1>
          <p>If you see this page, the nginx web server is successfully installed and
          working. Further configuration is required.</p>

          <p>For online documentation and support please refer to
          <a href="http://nginx.org/">nginx.org</a>.<br/>
          Commercial support is available at
          <a href="http://nginx.com/">nginx.com</a>.</p>

          <p><em>Thank you for using nginx.</em></p>
          </body>
          </html>
