apiVersion: cluster.open-cluster-management.io/v1beta1
kind: Placement
metadata:
  name: placement1
  namespace: default
spec:
  predicates:
  - requiredClusterSelector:
      labelSelector:
        matchLabels:
          vendor: Kind
