apiVersion: edge.limani.kube/v1alpha1
kind: ConfigSpec
metadata:
  name: bar
spec:
  content:
  - YXBpVmVyc2lvbjogYXBwcy92MQpraW5kOiBEZXBsb3ltZW50Cm1ldGFkYXRhOgogIG5hbWU6IGd1ZXN0Ym9vay11aQpzcGVjOgogIHJlcGxpY2FzOiAxCiAgcmV2aXNpb25IaXN0b3J5TGltaXQ6IDMKICBzZWxlY3RvcjoKICAgIG1hdGNoTGFiZWxzOgogICAgICBhcHA6IGd1ZXN0Ym9vay11aQogIHRlbXBsYXRlOgogICAgbWV0YWRhdGE6CiAgICAgIGxhYmVsczoKICAgICAgICBhcHA6IGd1ZXN0Ym9vay11aQogICAgc3BlYzoKICAgICAgY29udGFpbmVyczoKICAgICAgLSBpbWFnZTogZ2NyLmlvL2hlcHRpby1pbWFnZXMva3MtZ3Vlc3Rib29rLWRlbW86MC4yCiAgICAgICAgbmFtZTogZ3Vlc3Rib29rLXVpCiAgICAgICAgcG9ydHM6CiAgICAgICAgLSBjb250YWluZXJQb3J0OiA4MAogICAgICAgIHJlc291cmNlczoKICAgICAgICAgIGxpbWl0czoKICAgICAgICAgICAgY3B1OiAxMDBtCiAgICAgICAgICAgIG1lbW9yeTogNjRNaQo=
  - YXBpVmVyc2lvbjogdjEKa2luZDogU2VydmljZQptZXRhZGF0YToKICBuYW1lOiBndWVzdGJvb2stdWkKc3BlYzoKICBwb3J0czoKICAtIHBvcnQ6IDgwCiAgICB0YXJnZXRQb3J0OiA4MAogIHNlbGVjdG9yOgogICAgYXBwOiBndWVzdGJvb2stdWkK
---
# https://github.com/redhat-et/AI-for-edge-microshift-demo
apiVersion: edge.limani.kube/v1alpha1
kind: ConfigSpec
metadata:
  name: ai4edge
spec:
  content:
  - aHR0cHM6Ly9naXRodWIuY29tL3JlZGhhdC1ldC9BSS1mb3ItZWRnZS1taWNyb3NoaWZ0LWRlbW8vcmF3L21haW4vc2VydmVyL2NhbS1zZXJ2ZXIueWFtbAo=
  - aHR0cHM6Ly9naXRodWIuY29tL3JlZGhhdC1ldC9BSS1mb3ItZWRnZS1taWNyb3NoaWZ0LWRlbW8vcmF3L21haW4vd2lmaS1hcC9jYW0tYXAueWFtbAo=
