apiVersion: edge.kyst.kube/v1alpha1
kind: ConfigSpec
metadata:
  name: bar
spec:
  content:
  - |
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: guestbook-ui
    spec:
      replicas: 1
      revisionHistoryLimit: 3
      selector:
        matchLabels:
          app: guestbook-ui
      template:
        metadata:
          labels:
            app: guestbook-ui
        spec:
          containers:
          - image: gcr.io/heptio-images/ks-guestbook-demo:0.2
            name: guestbook-ui
            ports:
            - containerPort: 80
            resources:
              limits:
                cpu: 100m
                memory: 64Mi
  - |
    apiVersion: v1
    kind: Service
    metadata:
      name: guestbook-ui
    spec:
      ports:
      - port: 80
        targetPort: 80
      selector:
        app: guestbook-ui
---
apiVersion: edge.kyst.kube/v1alpha1
kind: DeviceGroup
metadata:
  name: bar
spec:
  configSpecName: bar
---
apiVersion: edge.kyst.kube/v1alpha1
kind: InventoryDevice
metadata:
  name: bar
  labels:
    edge.kyst.kube/device-group-name: bar
